name: "😵‍💫 バグ報告"
description: "バグの詳細も記載してください"
labels: ["bug"]
projects: ["nre/2"]
title: "😵‍💫 [bug] タイトルをここに入力してください"
labels: [
  "bug"
]
body:
  - type: textarea
    id: bug_detail
    attributes:
      label: "バグ情報"
      value: |
        <!-- 簡潔に箇条書きで記載してください。 -->
        <!-- あとから履歴を辿っても内容が把握出来るようにしてください -->
        ## 概要
        -

        ## 発生日時
        - yyyy/mm/dd hh:mm

        ## 関係者
        -

        ## Slackやりとり
        - <URL>

        ## チケット
        - <URL>

        ## 利用OS/ブラウザ
        ```
        OS:
        ブラウザ:
        バージョン:
        ```

        ## 詳細
        ```

        ```

        ## 補足事項などあれば、こちらに記載ください
        -

    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "ログ"
      description: エラーログやエラーメッセージがあれば貼り付けてください
      placeholder: "エラーメッセージを貼り付けてください"
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: "スクリーンショット"
      description: "必要に応じて、こちらに貼り付けてください"
      value: "<!-- 複数ある場合、何のスクリーンショットなのか説明も追記ください --> \n"
      placeholder: "スクリーンショットが複数あれば適宜説明も記載してください"
    validations:
      required: false

