# Generated by Django 5.0.3 on 2024-03-31 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import dsbd.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("custom_auth", "0004_group_users_alter_user_groups"),
        ("router", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="作成日")),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="更新日")),
                (
                    "service_type",
                    models.IntegerField(
                        choices=[
                            ("2000", "L2"),
                            ("3S00", "L3 Static"),
                            ("3B00", "L3 BGP"),
                            ("IP3B", "トランジット提供"),
                            ("CL20", "コロケーションサービス(L2)"),
                            ("CL3S", "コロケーションサービス(L3 Static)"),
                            ("CL3B", "コロケーションサービス(L3 BGP)"),
                            ("ET00", "その他"),
                        ],
                        default="CL3B",
                        verbose_name="サービスタイプ",
                    ),
                ),
                ("service_number", models.IntegerField(default=0, verbose_name="サービス番号")),
                ("service_comment", models.IntegerField(blank=True, default=0, verbose_name="サービス情報コメント")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("is_pass", models.BooleanField(default=False, verbose_name="審査OK")),
                ("allow_connection_add", models.BooleanField(default=True, verbose_name="接続追加許可")),
                ("asn", models.IntegerField(blank=True, default=0, null=True, verbose_name="ASN")),
                ("ave_upstream", models.IntegerField(default=10, verbose_name="平均アップロード帯域幅")),
                ("max_upstream", models.IntegerField(default=20, verbose_name="最大アップロード帯域幅")),
                ("ave_downstream", models.IntegerField(default=10, verbose_name="平均ダウンロード帯域幅")),
                ("max_downstream", models.IntegerField(default=20, verbose_name="最大ダウンロード帯域幅")),
                (
                    "max_bandwidth_as",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="最大帯域幅AS"),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True, verbose_name="開通日")),
                ("end_at", models.DateTimeField(blank=True, null=True, verbose_name="解約日")),
                ("user_comment", dsbd.models.MediumTextField(blank=True, default="", verbose_name="ユーザコメント")),
                ("admin_comment", dsbd.models.MediumTextField(blank=True, default="", verbose_name="管理者コメント")),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ServiceGroup",
                        to="custom_auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="作成日")),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="更新日")),
                (
                    "connection_type",
                    models.IntegerField(
                        choices=[
                            ("EIP", "EtherIP Tunnel"),
                            ("GRE", "GRE Tunnel"),
                            ("IPT", "IPT Tunnel"),
                            ("CC0", "Cross Connect"),
                            ("ETC", "ETC"),
                        ],
                        default="EIP",
                        verbose_name="サービスタイプ",
                    ),
                ),
                ("connection_number", models.IntegerField(default=0, verbose_name="接続番号")),
                ("connection_comment", models.IntegerField(blank=True, default=0, verbose_name="接続情報コメント")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("is_open", models.BooleanField(default=False, verbose_name="開通")),
                (
                    "hope_location",
                    models.CharField(
                        choices=[("east_japan", "東日本"), ("west_japan", "西日本"), ("anywhere", "どちらでも")],
                        default="anywhere",
                        max_length=255,
                        verbose_name="接続希望場所",
                    ),
                ),
                (
                    "term_location",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="接続終端場所"),
                ),
                (
                    "ntt_type",
                    models.CharField(
                        choices=[
                            ("type-1", "はい（IPoEによりIPv6インターネットへ接続可能）"),
                            ("type-2", "はい（IPoEによりIPv6インターネットへ接続不可）"),
                            ("type-3", "はい（フレッツv6オプションの契約なし）"),
                            ("type-4", "いいえ（フレッツ以外でインターネットに接続可能）"),
                            ("type-5", "いいえ（IPv6でのインターネット接続不可）"),
                            ("etc", "etc"),
                        ],
                        default="type-1",
                        max_length=255,
                        verbose_name="NTT接続タイプ",
                    ),
                ),
                (
                    "ntt_comment",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="NTT接続コメント"),
                ),
                (
                    "ipv4_route",
                    models.CharField(
                        choices=[
                            ("full_route", "Full Route"),
                            ("default_route", "Default Route"),
                            ("full_route", "Etc"),
                        ],
                        default="full_route",
                        max_length=255,
                        verbose_name="IPv4 Route",
                    ),
                ),
                ("ipv4_comment", models.CharField(blank=True, default="", max_length=255, verbose_name="IPv4コメント")),
                (
                    "ipv6_route",
                    models.CharField(
                        choices=[
                            ("full_route", "Full Route"),
                            ("default_route", "Default Route"),
                            ("full_route", "Etc"),
                        ],
                        default="full_route",
                        max_length=255,
                        verbose_name="IPv6 Route",
                    ),
                ),
                ("ipv6_comment", models.CharField(blank=True, default="", max_length=255, verbose_name="IPv6コメント")),
                ("is_monitor", models.BooleanField(default=False, verbose_name="監視の有無")),
                (
                    "link_v4_our",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IPv4接続(HomeNOC側)"),
                ),
                ("link_v4_your", models.GenericIPAddressField(blank=True, null=True, verbose_name="IPv4(貴団体側)")),
                (
                    "link_v6_our",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IPv6接続(HomeNOC側)"),
                ),
                ("link_v6_your", models.GenericIPAddressField(blank=True, null=True, verbose_name="IPv6(貴団体側)")),
                ("term_ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="終端先IP")),
                ("start_at", models.DateTimeField(blank=True, null=True, verbose_name="開通日")),
                ("end_at", models.DateTimeField(blank=True, null=True, verbose_name="解約日")),
                ("user_comment", dsbd.models.MediumTextField(blank=True, default="", verbose_name="ユーザコメント")),
                ("admin_comment", dsbd.models.MediumTextField(blank=True, default="", verbose_name="管理者コメント")),
                (
                    "tunnel_ip",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ConnectionTunnelIP",
                        to="router.tunnelip",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ConnectionService",
                        to="service.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connection",
                "verbose_name_plural": "Connections",
                "ordering": ("id",),
            },
        ),
    ]
