# Generated by Django 5.0.3 on 2024-03-31 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("router", "0001_initial"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connection",
            name="ipv4_comment",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="ipv6_comment",
        ),
        migrations.AddField(
            model_name="connection",
            name="ipv4_route_comment",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="IPv4 Routeコメント"),
        ),
        migrations.AddField(
            model_name="connection",
            name="ipv6_route_comment",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="IPv6 Routeコメント"),
        ),
        migrations.AlterField(
            model_name="connection",
            name="connection_comment",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="接続情報コメント"),
        ),
        migrations.AlterField(
            model_name="connection",
            name="connection_number",
            field=models.IntegerField(default=1, verbose_name="接続番号"),
        ),
        migrations.AlterField(
            model_name="connection",
            name="connection_type",
            field=models.CharField(
                choices=[
                    ("EIP", "EtherIP Tunnel"),
                    ("GRE", "GRE Tunnel"),
                    ("IPT", "IPT Tunnel"),
                    ("CC0", "Cross Connect"),
                    ("ETC", "ETC"),
                ],
                default="EIP",
                max_length=255,
                verbose_name="接続タイプ",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="ipv4_route",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("full_route", "Full Route"),
                    ("default_route", "Default Route"),
                    ("full_route", "Etc"),
                ],
                default="full_route",
                max_length=255,
                verbose_name="IPv4 Route",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="ipv6_route",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("full_route", "Full Route"),
                    ("default_route", "Default Route"),
                    ("full_route", "Etc"),
                ],
                default="full_route",
                max_length=255,
                verbose_name="IPv6 Route",
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="tunnel_ip",
            field=models.ForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ConnectionTunnelIP",
                to="router.tunnelip",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_comment",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="サービス情報コメント"),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_number",
            field=models.IntegerField(default=1, verbose_name="サービス番号"),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("2000", "L2"),
                    ("3S00", "L3 Static"),
                    ("3B00", "L3 BGP"),
                    ("IP3B", "トランジット提供"),
                    ("CL20", "コロケーションサービス(L2)"),
                    ("CL3S", "コロケーションサービス(L3 Static)"),
                    ("CL3B", "コロケーションサービス(L3 BGP)"),
                    ("ET00", "その他"),
                ],
                default="CL3B",
                max_length=255,
                verbose_name="サービスタイプ",
            ),
        ),
    ]
