# Generated by Django 5.0.3 on 2024-03-31 08:50

import django.utils.timezone
import dsbd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('subnet', models.IntegerField(default=32, verbose_name='サブネット')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='開通日')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='解約日')),
                ('plan', models.JSONField(blank=True, null=True, verbose_name='プラン')),
                ('use_case', dsbd.models.MediumTextField(default='', verbose_name='使用用途')),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'IPs',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='IPJPNICUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('user_type', models.CharField(choices=[('admin', '管理者'), ('tech1', '技術担当者1'), ('tech2', '技術担当者2'), ('tech3', '技術担当者3'), ('tech4', '技術担当者4'), ('tech5', '技術担当者5')], default='admin', max_length=255, verbose_name='タイプ')),
            ],
            options={
                'verbose_name': 'IP・JPNIC User',
                'verbose_name_plural': 'IP・JPNIC Users',
            },
        ),
        migrations.CreateModel(
            name='JPNICUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('hidden', models.BooleanField(default=False, verbose_name='隠蔽')),
                ('handle_type', models.CharField(choices=[('group_handle', 'グループハンドル'), ('jpnic_handle', 'JPNICハンドル')], default='jpnic_handle', max_length=255, verbose_name='ハンドルタイプ')),
                ('jpnic_handle', models.CharField(blank=True, max_length=100, verbose_name='JPNIC Handle')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('name_jp', models.CharField(max_length=150, verbose_name='name(japanese)')),
                ('email', models.EmailField(max_length=150, verbose_name='E-Mail')),
                ('org', models.CharField(max_length=150, unique=True, verbose_name='Org')),
                ('org_jp', models.CharField(max_length=150, verbose_name='Org(japanese)')),
                ('postcode', models.CharField(default='', max_length=20, verbose_name='郵便番号')),
                ('address', models.CharField(default='', max_length=250, verbose_name='住所')),
                ('address_jp', models.CharField(default='', max_length=250, verbose_name='住所(Japanese)')),
                ('dept', models.CharField(blank=True, default='', max_length=250, verbose_name='部署')),
                ('dept_jp', models.CharField(blank=True, default='', max_length=250, verbose_name='部署(Japanese)')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='役職')),
                ('title_jp', models.CharField(blank=True, default='', max_length=250, verbose_name='役職(Japanese)')),
                ('tel', models.CharField(default='', max_length=30, verbose_name='tel')),
                ('fax', models.CharField(default='', max_length=30, verbose_name='fax')),
                ('country', models.CharField(default='Japan', max_length=100, verbose_name='居住国')),
            ],
            options={
                'verbose_name': 'JPNIC User',
                'verbose_name_plural': 'JPNIC Users',
                'ordering': ('id',),
            },
        ),
    ]
