# Generated by Django 5.0.3 on 2024-03-31 19:19

from django.db import migrations, models

import dsbd.models


class Migration(migrations.Migration):
    dependencies = [
        ("ip", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ip",
            name="owner",
            field=models.CharField(
                choices=[("form_our", "当団体から割当"), ("form_your", "貴団体から割当")],
                default="form_our",
                max_length=255,
                verbose_name="アドレス所持オーナ",
            ),
        ),
        migrations.AlterField(
            model_name="ip",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name="IP Address"),
        ),
        migrations.AlterField(
            model_name="ip",
            name="use_case",
            field=dsbd.models.MediumTextField(blank=True, default="", verbose_name="使用用途"),
        ),
        migrations.AlterField(
            model_name="jpnicuser",
            name="fax",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="fax"),
        ),
    ]
