# Generated by Django 5.1.1 on 2024-09-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_alter_group_status'),
        ('ip', '0003_ip_owner_alter_ip_ip_address_alter_ip_use_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpnicuser',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JPNICUserGroup', to='custom_auth.group'),
        ),
    ]
