# Generated by Django 5.1.1 on 2024-09-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0005_remove_jpnicuser_is_active_jpnicuser_is_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpnicuser',
            name='is_pass',
            field=models.BooleanField(default=False, verbose_name='審査OK'),
        ),
    ]
