# Generated by Django 5.1.1 on 2024-09-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0006_alter_jpnicuser_is_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='plan',
        ),
        migrations.AddField(
            model_name='ip',
            name='ipv4_plan',
            field=models.JSONField(blank=True, null=True, verbose_name='IPv4プラン'),
        ),
        migrations.AddField(
            model_name='ip',
            name='is_pass',
            field=models.BooleanField(default=False, verbose_name='審査OK'),
        ),
    ]
