# Generated by Django 5.1.1 on 2024-09-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0007_remove_ip_plan_ip_ipv4_plan_ip_is_pass'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipjpnicuser',
            unique_together={('jpnic_user', 'ip', 'user_type')},
        ),
    ]
