# Generated by Django 5.1.1 on 2024-09-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_group_allow_jpnic_add'),
        ('ip', '0009_jpnicuser_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jpnicuser',
            unique_together={('group', 'jpnic_handle', 'version', 'name', 'name_jp')},
        ),
    ]
