# Generated by Django 5.1.1 on 2024-09-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0010_alter_jpnicuser_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jpnicuser',
            name='org',
            field=models.CharField(max_length=150, verbose_name='Org'),
        ),
    ]
