# Generated by Django 5.1.1 on 2024-09-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0011_alter_jpnicuser_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='version',
            field=models.IntegerField(choices=[(4, 'IPv4'), (6, 'IPv6')], default=4, verbose_name='IPバージョン'),
        ),
    ]
