# Generated by Django 5.1.1 on 2024-09-14 20:33

import django.db.models.deletion
import django.utils.timezone
import dsbd.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_historicalgroup_historicaluser_historicalusergroup'),
        ('ip', '0013_alter_ip_ip_address'),
        ('service', '0003_historicalconnection_historicalservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIP',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_pass', models.BooleanField(default=False, verbose_name='審査OK')),
                ('version', models.IntegerField(choices=[(4, 'IPv4'), (6, 'IPv6')], default=4, verbose_name='IPバージョン')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('subnet', models.IntegerField(default=32, verbose_name='サブネット')),
                ('owner', models.CharField(choices=[('form_our', '当団体から割当'), ('form_your', '貴団体から割当')], default='form_our', max_length=255, verbose_name='アドレス所持オーナ')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='開通日')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='解約日')),
                ('ipv4_plan', models.JSONField(blank=True, null=True, verbose_name='IPv4プラン')),
                ('use_case', dsbd.models.MediumTextField(blank=True, default='', verbose_name='使用用途')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='service.service')),
            ],
            options={
                'verbose_name': 'historical IP',
                'verbose_name_plural': 'historical IPs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIPJPNICUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('user_type', models.CharField(choices=[('admin', '管理者'), ('tech1', '技術担当者1'), ('tech2', '技術担当者2'), ('tech3', '技術担当者3'), ('tech4', '技術担当者4'), ('tech5', '技術担当者5')], default='admin', max_length=255, verbose_name='タイプ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ip', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ip.ip')),
                ('jpnic_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ip.jpnicuser')),
            ],
            options={
                'verbose_name': 'historical IP・JPNIC User',
                'verbose_name_plural': 'historical IP・JPNIC Users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalJPNICUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('is_pass', models.BooleanField(default=False, verbose_name='審査OK')),
                ('hidden', models.BooleanField(default=False, verbose_name='隠蔽')),
                ('handle_type', models.CharField(choices=[('group_handle', 'グループハンドル'), ('jpnic_handle', 'JPNICハンドル')], default='jpnic_handle', max_length=255, verbose_name='ハンドルタイプ')),
                ('version', models.IntegerField(choices=[(4, 'IPv4'), (6, 'IPv6')], default=4, verbose_name='IPバージョン')),
                ('jpnic_handle', models.CharField(blank=True, max_length=100, verbose_name='JPNIC Handle')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('name_jp', models.CharField(max_length=150, verbose_name='name(japanese)')),
                ('email', models.EmailField(max_length=150, verbose_name='E-Mail')),
                ('org', models.CharField(max_length=150, verbose_name='Org')),
                ('org_jp', models.CharField(max_length=150, verbose_name='Org(japanese)')),
                ('postcode', models.CharField(default='', max_length=20, verbose_name='郵便番号')),
                ('address', models.CharField(default='', max_length=250, verbose_name='住所')),
                ('address_jp', models.CharField(default='', max_length=250, verbose_name='住所(Japanese)')),
                ('dept', models.CharField(blank=True, default='', max_length=250, verbose_name='部署')),
                ('dept_jp', models.CharField(blank=True, default='', max_length=250, verbose_name='部署(Japanese)')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='役職')),
                ('title_jp', models.CharField(blank=True, default='', max_length=250, verbose_name='役職(Japanese)')),
                ('tel', models.CharField(default='', max_length=30, verbose_name='tel')),
                ('fax', models.CharField(blank=True, default='', max_length=30, verbose_name='fax')),
                ('country', models.CharField(default='Japan', max_length=100, verbose_name='居住国')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='custom_auth.group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical JPNIC User',
                'verbose_name_plural': 'historical JPNIC Users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
