# Generated by Django 4.2.7 on 2023-11-26 12:06

import uuid

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import custom_auth.models
import dsbd.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="作成日")),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="更新日")),
                (
                    "username",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "username_jp",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username(japanese)",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                ("is_staff", models.BooleanField(default=False, verbose_name="管理者ステータス")),
                ("is_active", models.BooleanField(default=False, verbose_name="有効")),
            ],
            options={
                "verbose_name": "ユーザ",
                "verbose_name_plural": "ユーザ",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="作成日")),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="更新日")),
                ("name", models.CharField(max_length=150, unique=True, verbose_name="name")),
                ("name_jp", models.CharField(max_length=150, unique=True, verbose_name="name(japanese)")),
                ("comment", models.CharField(blank=True, default="", max_length=250, verbose_name="comment")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "有効"), (10, "ユーザより廃止"), (11, "運営委員より廃止"), (12, "審査落ち")],
                        default=0,
                        verbose_name="ステータス",
                    ),
                ),
                ("add_service", models.BooleanField(default=False, verbose_name="サービス追加許可")),
                (
                    "membership_type",
                    models.IntegerField(
                        choices=[
                            (1, "一般会員"),
                            (40, "運営委員(優勝)"),
                            (70, "学生委員"),
                            (90, "運営委員(無償)"),
                            (99, "その他"),
                        ],
                        default=1,
                        verbose_name="会員種別",
                    ),
                ),
                ("membership_expired_at", models.DateTimeField(blank=True, null=True, verbose_name="有効期限")),
                ("agree", models.BooleanField(default=False, verbose_name="規約確認済み")),
                ("question", dsbd.models.MediumTextField(default="", verbose_name="質問内容")),
                ("is_pass", models.BooleanField(default=False, verbose_name="審査OK")),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="Stripe(CusID)"),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=200, null=True, verbose_name="Stripe(SubID)"),
                ),
                ("postcode", models.CharField(default="", max_length=20, verbose_name="郵便番号")),
                ("address", models.CharField(default="", max_length=250, verbose_name="住所")),
                ("address_en", models.CharField(default="", max_length=250, verbose_name="住所(English)")),
                ("phone", models.CharField(default="", max_length=30, verbose_name="phone")),
                ("country", models.CharField(default="Japan", max_length=100, verbose_name="居住国")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[("E-Mail", "E-Mail"), ("AirMail", "AirMail)")],
                        default="E-Mail",
                        max_length=100,
                        verbose_name="契約種別",
                    ),
                ),
            ],
            options={
                "verbose_name": "グループ",
                "verbose_name_plural": "グループ",
            },
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="作成日")),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="更新日")),
                ("is_admin", models.BooleanField(default=False, verbose_name="管理者")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="custom_auth.group")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "ユーザ・グループ",
                "verbose_name_plural": "ユーザ・グループ",
                "unique_together": {("user", "group")},
            },
        ),
        migrations.CreateModel(
            name="UserEmailVerify",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="作成日")),
                ("token", models.CharField(max_length=100, verbose_name="token")),
                (
                    "expired_at",
                    models.DateTimeField(default=custom_auth.models.email_verify_expire_date, verbose_name="有効期限"),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="使用済み")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "E-Mail用のVerify",
                "verbose_name_plural": "E-Mail用のVerify",
            },
        ),
        migrations.CreateModel(
            name="UserActivateToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="作成日")),
                ("token", models.UUIDField(default=uuid.uuid4, verbose_name="Active token")),
                (
                    "expired_at",
                    models.DateTimeField(default=custom_auth.models.user_activate_expire_date, verbose_name="有効期限"),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="使用済み")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Activate用のToken",
                "verbose_name_plural": "Activate用のToken",
            },
        ),
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="作成日")),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("secret", models.CharField(max_length=100, verbose_name="secret")),
                ("is_active", models.BooleanField(default=False, verbose_name="有効")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "TOTP Device",
                "verbose_name_plural": "TOTP Device",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific Groups for this user.",
                related_name="user_set",
                related_query_name="user",
                through="custom_auth.UserGroup",
                to="custom_auth.group",
                verbose_name="groups",
            ),
        ),
    ]
