# Generated by Django 4.2.7 on 2023-11-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='display_name'),
        ),
    ]
