# Generated by Django 5.1.1 on 2024-09-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_alter_group_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allow_jpnic_add',
            field=models.BooleanField(default=False, verbose_name='JPNIC情報追加許可'),
        ),
    ]
