# Generated by Django 5.1.1 on 2024-09-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_historicalgroup_historicaluser_historicalusergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='historicalgroup',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='stripe_donate_customer_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe Donate(CusID)'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_donate_customer_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe Donate(CusID)'),
        ),
    ]
