# Generated by Django 5.0.3 on 2024-03-31 08:50

import django.utils.timezone
from django.db import migrations, models

import dsbd.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NOC",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="作成日")),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="更新日")),
                ("name", models.CharField(default="", max_length=255, verbose_name="名前")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("location", models.CharField(blank=True, default="", max_length=255, verbose_name="場所")),
                ("bandwidth", models.IntegerField(default=1000, verbose_name="帯域幅")),
                ("comment", dsbd.models.MediumTextField(blank=True, default="", verbose_name="コメント")),
            ],
            options={
                "verbose_name": "NOC",
                "verbose_name_plural": "NOCs",
                "ordering": ("id",),
            },
        ),
    ]
