# Generated by Django 5.1.1 on 2024-09-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnelip',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名前'),
        ),
    ]
